### PR TITLE
Added scaleText and fixed typings

### PR DESCRIPTION
**Pull request by zaguiini**
As discussed in #16

### CODE REVIEW

**Comment by zaguiini** [comment]
This time I didn't mess up with the `package.json` version, @knowbody ;)

**Comment by zaguiini** [comment]
It would be useful for me if this got merged

**Comment by knowbody** [comment]
I'll get it merged, one small nit pick: could you please use the default prettier settings (bring the semicolons back)?

**Comment by zaguiini** [comment]
Done.

**Comment by knowbody** [comment]
Thank you!

**Comment by zaguiini** [comment]
Don't forget to close #16

**Pull request merged**
