### PR TITLE
Added typings

### PR DESCRIPTION
**Pull request by zaguiini**
Just added typescript types

### CODE REVIEW

**Comment by zaguiini** [comment]
Hey @knowbody, can we merge it?

**Comment by knowbody** [comment]
Of course! Thank you and sorry for the delay

**Comment by knowbody** [comment]
Please keep the npm version as it was. I'll bump it up while releasing

**Comment by zaguiini** [comment]
Okay!

**Comment by knowbody** [comment]
sorry for the delay, just did the release: https://github.com/knowbody/react-native-text/releases/tag/v0.1.0

Thank you once again for your contribution! 🥇

**Pull request merged**
